// Code generated by "stringer -type=ValueType"; DO NOT EDIT

package mill

import "fmt"

const _ValueType_name = "ValueTypeUnknownValueTypeStringValueTypeInt64ValueTypeUint64ValueTypeFloat64ValueTypeAny"

var _ValueType_index = [...]uint8{0, 16, 31, 45, 60, 76, 88}

func (i ValueType) String() string {
	if i >= ValueType(len(_ValueType_index)-1) {
		return fmt.Sprintf("ValueType(%d)", i)
	}
	return _ValueType_name[_ValueType_index[i]:_ValueType_index[i+1]]
}
